# Generated by Django 5.2.5 on 2025-08-27 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Sin descripcion', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='dispositivos.zona'),
        ),
        migrations.AddField(
            model_name='zona',
            name='descripcion',
            field=models.TextField(default='Sin descripcion', max_length=100),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_medido', models.FloatField()),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='dispositivos.dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='dispositivos.categoria'),
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('consumo', models.FloatField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='dispositivos.dispositivo')),
            ],
        ),
    ]
